name: Code Compile

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/-1, lts/*, latest]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm pack